services:
  - type: web
    name: mentiby-attendance-backend
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_DEBUG
        value: false
      - key: PORT
        value: 10000
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
    disk:
      name: backend-disk
      mountPath: /tmp
      sizeGB: 1 